<?xml version="1.0"?>
<package format="3">
  <name>path_reuse_sm2</name>
  <version>0.1.0</version>
  <description>PRSM (Path Reuse-based State Machine) for ROS 2 Humble</description>
  <maintainer email="root@todo.todo">root</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>rclcpp</build_depend>
  <build_depend>rclpy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>std_srvs</build_depend>
  <build_depend>trajectory_msgs</build_depend>

  <exec_depend>rclcpp</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <!-- xArm dependencies -->
  <exec_depend>xarm_utils_cpp</exec_depend>
  <exec_depend>path_reuse_method</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <depend>yasmin</depend>
  <depend>yasmin_viewer</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
